# Generated by Django 5.0.6 on 2024-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100, verbose_name='سوال')),
                ('answer', models.TextField(max_length=100, verbose_name='پاسخ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در')),
            ],
            options={
                'verbose_name': 'فلش کارت',
                'verbose_name_plural': 'فلش کارتها',
            },
        ),
    ]
